# Generated by Django 3.2.9 on 2021-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('progress', models.IntegerField()),
                ('dependencies', models.CharField(max_length=50)),
                ('custom_class', models.CharField(max_length=50)),
            ],
        ),
    ]
